Rocco Rutte: - move svn revision grabbing to Makefile so that there's no longer a need to re-run configure for it to update - start to beautify 'muttng -v' output to list all libs w/ version numbers (maybe helps when debuging) - fix configure to look for one more ncurses header in $pfx/ncurses/ even for ncursesw (for FreeBSD via ports) so that lib and are from the same version - stop exiting if install can't chgrp dotlock's permissions; just warn instead

diff --git a/trunk/Makefile.am b/trunk/Makefile.am
--- a/trunk/Makefile.am
+++ b/trunk/Makefile.am
@@ -23,7 +23,7 @@ SUBDIRS = m4 po intl doc contrib lib $(IMAP_SUBDIR) $(POP_SUBDIR) $(NNTP_SUBDIR)
 
 bin_SCRIPTS = muttngbug fleang
 
-BUILT_SOURCES = keymap_defs.h patchlist.c
+BUILT_SOURCES = keymap_defs.h patchlist.c svnrev.h
 
 bin_PROGRAMS = muttng @DOTLOCK_TARGET@ @PGPAUX_TARGET@ @SMIMEAUX_TARGET@
 muttng_SOURCES = $(BUILT_SOURCES) \
@@ -125,7 +125,7 @@ mutt_dotlock.c: dotlock.c
 	cp $(srcdir)/dotlock.c mutt_dotlock.c
 
 CLEANFILES = mutt_dotlock.c stamp-doc-rc makedoc \
-	keymap_alldefs.h keymap_defs.h patchlist.c
+	keymap_alldefs.h keymap_defs.h patchlist.c svnrev.h
 
 ACLOCAL_AMFLAGS = -I m4
 
@@ -151,6 +151,13 @@ keymap_alldefs.h: $(srcdir)/OPS $(srcdir)/OPS.PGP $(srcdir)/OPS.MIX $(srcdir)/OP
 		$(srcdir)/OPS.MIX $(srcdir)/OPS.CRYPT $(srcdir)/OPS.SMIME \
 			> keymap_alldefs.h
 
+svnrev.h:
+	if test -f "$(srcdir)/.svn/entries" ; then \
+	  echo "#define MUTTNG_SVNREV \"r`grep revision $(srcdir)/.svn/entries | sort -r | uniq | head -n 1 | cut -d '"' -f 2`\"" > svnrev.h ; \
+	else \
+	  echo "#define MUTTNG_SVNREV \"`date "+%Y%m%d"`\"" > svnrev.h ; \
+	fi
+
 reldate:
 	echo 'const char *ReleaseDate = "'`date +%Y-%m-%d`'";' > $(srcdir)/reldate.h
 
@@ -165,7 +172,7 @@ install-exec-hook:
 	if test -f $(DESTDIR)$(bindir)/muttng_dotlock && test x@DOTLOCK_GROUP@ != x ; then \
 		chgrp @DOTLOCK_GROUP@ $(DESTDIR)$(bindir)/muttng_dotlock && \
 		chmod @DOTLOCK_PERMISSION@ $(DESTDIR)$(bindir)/muttng_dotlock || \
-		{ echo "Can't fix muttng_dotlock's permissions!" >&2 ; exit 1 ; } \
+		{ echo "Can't fix muttng_dotlock's permissions!" >&2 ; } \
 	fi
 
 install-data-local: Muttngrc
