Andreas Krennmair: 	changed mutt to muttng, .muttrc to .muttngrc and Muttrc to Muttngrc to make it possible to have mutt and mutt-ng installed at the same time with different configurations

diff --git a/trunk/muttbug.sh.in b/trunk/muttbug.sh.in
--- a/trunk/muttbug.sh.in
+++ b/trunk/muttbug.sh.in
@@ -272,7 +272,7 @@ if test "$CORE" && test -f "$CORE" ; then
 fi
 
 if test "$personal" = "yes" ; then
-	CANDIDATES=".muttrc-${MUTTVERSION} .muttrc .mutt/muttrc-${MUTTVERSION} .mutt/muttrc"
+	CANDIDATES=".muttngrc-${MUTTVERSION} .muttngrc .muttng/muttngrc-${MUTTVERSION} .muttng/muttngrc"
 	MATCHED="none"
 	for f in $CANDIDATES; do
 		if test -f "${HOME}/$f" ; then
@@ -282,7 +282,7 @@ if test "$personal" = "yes" ; then
 	done
 	
 	if test "$MATCHED" = "none" ; then
-		echo "Warning: Can't find your personal .muttrc." >&2
+		echo "Warning: Can't find your personal .muttngrc." >&2
 	else
 		include_file $MATCHED
 	fi
@@ -290,7 +290,7 @@ fi
 
 
 if test "$global" = "yes" ; then
-	CANDIDATES="Muttrc-${MUTTVERSION} Muttrc"
+	CANDIDATES="Muttngrc-${MUTTVERSION} Muttngrc"
 	DIRECTORIES="$sysconfdir $pkgdatadir"
 	MATCHED="none"
 	for d in $DIRECTORIES ; do
@@ -304,7 +304,7 @@ if test "$global" = "yes" ; then
 	done
 	
 	if test "$MATCHED" = "none" ; then
-		echo "Warning: Can't find global Muttrc." >&2
+		echo "Warning: Can't find global Muttngrc." >&2
 	else
 		include_file $MATCHED
 	fi
